# Generated by Django 5.0.6 on 2024-06-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_color_size_alter_products_product_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-CreatedDate', 'ProductID'), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('ProductCode', 'ProductID')},
        ),
        migrations.AlterModelTable(
            name='products',
            table='products_product',
        ),
    ]
