# Generated by Django 5.0.6 on 2024-11-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_delivery_paymentmethod_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='district',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
