# Generated by Django 5.0.6 on 2024-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_delivery_address_delivery_district_delivery_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='Card',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='UPI_Payment',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cash_delivery',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('cod', 'Cash on Delivery')], default='cod', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
